<?php
return [
    'web_name'=>'预约管理',
    'short_name'=>'SASU',
    'version'=>'V1.0',
    'res'=>[
        //cdn资源
        'font_awesome'=>'/css/font-awesome/css/font-awesome.min.css',
        'bootstrap_css'=>'/css/bootstrap.min.css',
        'bootstrap_js'=>'/js/bootstrap.min.js',
        'jquery'=>'/js/jquery.min.js',
        'admin_css'=>'https://ssyl.oss-cn-shenzhen.aliyuncs.com/res/css/AdminLTE.min.css',
        'admin_js'=>'/js/adminlte.min.js',
        //主题皮肤
        'admin_skin'=>'/css/skins/skin-green.min.css',
        'app_skin'=>'skin-green',
        //兼容
        'html5shiv'=>'https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js',
        'respond'=>'https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js',
    ],
    'permission_deny'=>'你没有操作权限',
];