<?php
return [
    'web_name'=>'预约管理',
    'short_name'=>'SASU',
    'version'=>'V1.0',
    'res'=>[
        //cdn资源
        'font_awesome'=>'https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css',
        'bootstrap_css'=>'/css/bootstrap.min.css',
        'bootstrap_js'=>'/js/bootstrap.min.js',
        'jquery'=>'/js/jquery.min.js',
        'admin_css'=>'https://ssyl.oss-cn-shenzhen.aliyuncs.com/res/css/AdminLTE.min.css',
        'admin_js'=>'/js/adminlte.min.js',
        //主题皮肤
        'admin_skin'=>'/css/skin-green.min.css',
        'app_skin'=>'skin-green',
        //兼容
        'html5shiv'=>'/js/html5shiv.min.js',
        'respond'=>'/js/respond.min.js',
    ],
    'permission_deny'=>'你没有操作权限',
];